name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into Server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22 
        run: |
          cd /var/www/html/CafeV2
          echo "Working directory: $(pwd)"
          sudo git pull https://github.com/ecocle/CafeV2 main
          echo "Git pull finished"            
          npm install
          echo "NPM install finished"
          sudo chown -R ubuntu:ubuntu ./
          echo "File ownership changed"
          npm run build
          echo "Build finished"
          sudo chown -R www-data:www-data dist
          echo "Dist directory ownership changed"
          sudo systemctl restart CafeV2
          echo "Service restarted"
